Javascript/javascript3/week1
arya56/hyf-homework pull request #20
Opened 2020-09-18 13:32 UTC by arya56

2020-09-21 19:06 UTC, bashirmja commented
Hi Arya, 
I am going to review your code but I saw that you just included all files from other weeks and therefore I think you should clean up your branch. 
So can you please delete all files from your branch which is not related to this homework?
Thanks 
Bashir

2020-09-21 19:23 UTC, bashirmja requested changes
Besides those small commented codes, the rest looks good. As mentioned please remove other files not related to this week's homework.

2020-09-21 19:23 UTC, bashirmja commented on javascript/javascript3/week1/weather.html
> +    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
Please remove the commented code in lines 4  and 6.

2020-09-21 19:23 UTC, bashirmja commented on javascript/javascript3/week1/style.css
> +/* .center2 {
Also, remove commented css code here and at line 24.

2020-09-21 19:23 UTC, bashirmja commented on javascript/javascript3/week1/cityWeather.js
> +                // Optional a map showing where the city is located
I am not sure if we need also these comments.

2020-09-23 18:24 UTC, arya56 commented
I applied all reviews!

2020-09-23 18:24 UTC, merged