javascript/javascript3/week1
arya56/hyf-homework pull request #25
Opened 2020-09-29 11:11 UTC by arya56

2020-09-30 19:20 UTC, bashirmja requested changes
Great job. I made a few small comments. Please remember to delete commented code in CSS, js, and HTML files. 
in addition, still you need to consider the right indent for your code.
 well done

2020-09-30 19:20 UTC, bashirmja commented on javascript/javascript3/week1/GiphyApi.js
> +const button = document.querySelector('button')
It is recommended to create a class for button and use it in js file instead of using a tag name

2020-09-30 19:20 UTC, bashirmja commented on javascript/javascript3/week1/GiphyApi.js
> +      button.addEventListener('click',searchButton)
I am not sure if you need every time adding the event listener. you can add it in the line 8.

2020-09-30 19:20 UTC, bashirmja commented on javascript/javascript3/week1/style.css
> +    /* margin : 10px;
remember to remove all commented code in your branch.

2020-09-30 19:20 UTC, bashirmja commented on javascript/javascript3/week1/giphyindex.html
> +    <div id="center">
might be nice to have a better id because center is not a proper name for div.

2020-10-01 08:40 UTC, Ashwini-Metgudmath reviewed
Over all great job!  very good logic and you have written specific clean functions for each action, that's really good. 
Just need to focus on code formatting/indentation and naming convention. 
use icon property returned from api to render weather icon.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +function weatherToMyChoice(){
Try to give better name for function, It should be action or verb describing what it does.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +WeatherLocationButton.addEventListener('click', weatherLocationCapture)
Try to use camelCase for variable names

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +}}
Code indentation is very important, it helps other developer to read your code easily. so try format your code using tool like prettier or beautifier.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +    })}
must do code indentation.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> + }
Can find better name for function. 
suggestion:
standard nams like "renderData", "renderOutput" or can be more specific like "renderWeatherData" can be used for functions which render the data on browser.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +}
No required to create your own function to render icon, icon is already returned by api. you can create image tag in render function and using "http://openweathermap.org/img/w/${iconCode}.png"  url for src. here "iconCode" is just placeholder, you need to get icon property returned from api and replace in url.

2020-10-01 08:40 UTC, Ashwini-Metgudmath commented on javascript/javascript3/week1/cityWeather.js
> +}
Needs code format/indentation.

2020-10-10 20:10 UTC, bashirmja approved these changes

2020-10-10 20:11 UTC, bashirmja commented
Approved. Ready to merge if you are done with this pr.

2020-10-19 11:33 UTC, merged